### ISSUE TITLE
node-sass build error in docker

### ISSUE THREAD

**Issue by SOunit** [SOunit/node_react_web_chat#5]
# error
when build, error

# error log
see comment

# how to fix
use below

FROM node:10-alpine

# refs
https://github.com/sass/node-sass/issues/2165

**Comment by SOunit** [comment]
=> ERROR [4/5] RUN npm install                                                                                                                120.4s
------                                                                                                                                                
 > [4/5] RUN npm install:                                                                                                                             
#9 72.47 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated                                                         
#9 72.48 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated                                                      
#9 74.64 npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained                            
#9 74.75 npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained                              
#9 76.26 npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
#9 77.37 npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
#9 79.92 npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
#9 81.51 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#9 82.25 npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
#9 84.36 npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
#9 85.67 npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
#9 86.11 npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
#9 93.45 npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
#9 97.56 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#9 97.65 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#9 97.66 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
#9 98.72 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#9 99.82 npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
#9 106.0 npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
#9 106.4 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#9 108.0 npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
#9 112.3 npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
#9 120.2 npm notice 
#9 120.2 npm notice New minor version of npm available! 7.21.1 -> 7.23.0
#9 120.2 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.23.0>
#9 120.2 npm notice Run `npm install -g npm@7.23.0` to update!
#9 120.2 npm notice 
#9 120.2 npm ERR! code 1
#9 120.2 npm ERR! path /app/node_modules/node-sass
#9 120.2 npm ERR! command failed
#9 120.2 npm ERR! command sh -c node scripts/build.js
#9 120.2 npm ERR! Building: /usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#9 120.2 npm ERR! gyp info it worked if it ends with ok
#9 120.2 npm ERR! gyp verb cli [
#9 120.2 npm ERR! gyp verb cli   '/usr/local/bin/node',
#9 120.2 npm ERR! gyp verb cli   '/app/node_modules/node-gyp/bin/node-gyp.js',
#9 120.2 npm ERR! gyp verb cli   'rebuild',
#9 120.2 npm ERR! gyp verb cli   '--verbose',
#9 120.2 npm ERR! gyp verb cli   '--libsass_ext=',
#9 120.2 npm ERR! gyp verb cli   '--libsass_cflags=',
#9 120.2 npm ERR! gyp verb cli   '--libsass_ldflags=',
#9 120.2 npm ERR! gyp verb cli   '--libsass_library='
#9 120.2 npm ERR! gyp verb cli ]
#9 120.2 npm ERR! gyp info using node-gyp@3.8.0
#9 120.2 npm ERR! gyp info using node@16.9.1 | linux | x64
#9 120.2 npm ERR! gyp verb command rebuild []
#9 120.2 npm ERR! gyp verb command clean []
#9 120.2 npm ERR! gyp verb clean removing "build" directory
#9 120.2 npm ERR! gyp verb command configure []
#9 120.2 npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
#9 120.2 npm ERR! gyp verb `which` failed Error: not found: python2
#9 120.2 npm ERR! gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#9 120.2 npm ERR! gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
#9 120.2 npm ERR! gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#9 120.2 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
#9 120.2 npm ERR! gyp verb `which` failed  python2 Error: not found: python2
#9 120.2 npm ERR! gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#9 120.2 npm ERR! gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
#9 120.2 npm ERR! gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#9 120.2 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
#9 120.2 npm ERR! gyp verb `which` failed   code: 'ENOENT'
#9 120.2 npm ERR! gyp verb `which` failed }
#9 120.2 npm ERR! gyp verb check python checking for Python executable "python" in the PATH
#9 120.2 npm ERR! gyp verb `which` failed Error: not found: python
#9 120.2 npm ERR! gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#9 120.2 npm ERR! gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
#9 120.2 npm ERR! gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#9 120.2 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
#9 120.2 npm ERR! gyp verb `which` failed  python Error: not found: python
#9 120.2 npm ERR! gyp verb `which` failed     at getNotFoundError (/app/node_modules/which/which.js:13:12)
#9 120.2 npm ERR! gyp verb `which` failed     at F (/app/node_modules/which/which.js:68:19)
#9 120.2 npm ERR! gyp verb `which` failed     at E (/app/node_modules/which/which.js:80:29)
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/which/which.js:89:16
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/index.js:42:5
#9 120.2 npm ERR! gyp verb `which` failed     at /app/node_modules/isexe/mode.js:8:5
#9 120.2 npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
#9 120.2 npm ERR! gyp verb `which` failed   code: 'ENOENT'
#9 120.2 npm ERR! gyp verb `which` failed }
#9 120.2 npm ERR! gyp ERR! configure error 
#9 120.2 npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#9 120.2 npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/app/node_modules/node-gyp/lib/configure.js:484:19)
#9 120.2 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/configure.js:406:16)
#9 120.2 npm ERR! gyp ERR! stack     at F (/app/node_modules/which/which.js:68:16)
#9 120.2 npm ERR! gyp ERR! stack     at E (/app/node_modules/which/which.js:80:29)
#9 120.2 npm ERR! gyp ERR! stack     at /app/node_modules/which/which.js:89:16
#9 120.2 npm ERR! gyp ERR! stack     at /app/node_modules/isexe/index.js:42:5
#9 120.2 npm ERR! gyp ERR! stack     at /app/node_modules/isexe/mode.js:8:5
#9 120.2 npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
#9 120.2 npm ERR! gyp ERR! System Linux 5.10.47-linuxkit
#9 120.2 npm ERR! gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#9 120.2 npm ERR! gyp ERR! cwd /app/node_modules/node-sass
#9 120.2 npm ERR! gyp ERR! node -v v16.9.1
#9 120.2 npm ERR! gyp ERR! node-gyp -v v3.8.0
#9 120.2 npm ERR! gyp ERR! not ok 
#9 120.2 npm ERR! Build failed with error code: 1
#9 120.3 
#9 120.3 npm ERR! A complete log of this run can be found in:
#9 120.3 npm ERR!     /root/.npm/_logs/2021-09-15T00_50_10_685Z-debug.log
------
executor failed running [/bin/sh -c npm install]: exit code: 1

**Comment by SOunit** [comment]
error solved

**Comment by led101** [comment]
How did you solve this error? I have the same error

**Comment by led101** [comment]
Nevermind I fixed it by just updating all the outdated dependencies
